openapi: 3.0.0
info:
  title: シンプルなユーザー管理API
  description: ユーザー情報を管理するためのシンプルなAPI
  version: 1.0.0

servers:
  - url: http://localhost:23000
    description: 開発用サーバー

paths:
  /:
    get:
      summary: ウェルカムメッセージの取得
      description: APIのウェルカムメッセージを返します
      responses:
        '200':
          description: 正常にメッセージを取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WelcomeResponse'

  /users:
    get:
      summary: ユーザー一覧の取得
      description: 登録されている全ユーザーの一覧を返します
      responses:
        '200':
          description: 正常にユーザー一覧を取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersResponse'

    post:
      summary: 新規ユーザーの作成
      description: 新しいユーザーを登録します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateRequest'
      responses:
        '201':
          description: ユーザーの作成が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreatedResponse'
        '400':
          description: 不正なリクエストデータ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{id}:
    get:
      summary: 特定のユーザーの取得
      description: 指定されたIDのユーザー情報を取得します
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザーID
      responses:
        '200':
          description: ユーザーの取得が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: 指定されたユーザーが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /product-categories:
    get:
      summary: 商品カテゴリ一覧の取得
      description: 登録されている全商品カテゴリの一覧を返します
      responses:
        '200':
          description: 正常に商品カテゴリ一覧を取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoriesResponse'

    post:
      summary: 新規商品カテゴリの作成
      description: 新しい商品カテゴリを登録します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCategoryCreateRequest'
      responses:
        '201':
          description: 商品カテゴリの作成が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoryCreatedResponse'
        '400':
          description: 不正なリクエストデータ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /product-categories/{id}:
    get:
      summary: 特定の商品カテゴリの取得
      description: 指定されたIDの商品カテゴリ情報を取得します
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 商品カテゴリID
      responses:
        '200':
          description: 商品カテゴリの取得が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoryResponse'
        '404':
          description: 指定された商品カテゴリが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: 商品カテゴリの更新
      description: 商品カテゴリの情報を更新します
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 更新する商品カテゴリのID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCategoryUpdateRequest'
      responses:
        '200':
          description: 商品カテゴリの更新が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoryUpdatedResponse'
        '400':
          description: 不正なリクエストデータ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 指定された商品カテゴリが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: 商品カテゴリの削除
      description: 商品カテゴリを削除します
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 商品カテゴリID
      responses:
        '200':
          description: 商品カテゴリの削除が成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCategoryDeletedResponse'
        '404':
          description: 指定された商品カテゴリが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: ユーザーID
        name:
          type: string
          description: ユーザーの名前

    ProductCategory:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: 商品カテゴリID
        name:
          type: string
          description: 商品カテゴリの名前
        description:
          type: string
          description: 商品カテゴリの説明

    UserCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 登録するユーザーの名前

    ProductCategoryCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 登録する商品カテゴリの名前
        description:
          type: string
          description: 登録する商品カテゴリの説明

    ProductCategoryUpdateRequest:
      type: object
      properties:
        name:
          type: string
          description: 更新データ（商品カテゴリの名前）
        description:
          type: string
          description: 更新データ（商品カテゴリの説明）

    WelcomeResponse:
      type: object
      properties:
        message:
          type: string
          example: "Hello, Node.js!"

    UsersResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/User'

    UserResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/User'

    UserCreatedResponse:
      type: object
      properties:
        message:
          type: string
          example: "ユーザーの作成が完了しました"
        data:
          $ref: '#/components/schemas/User'

    ProductCategoriesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProductCategory'

    ProductCategoryResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ProductCategory'

    ProductCategoryCreatedResponse:
      type: object
      properties:
        message:
          type: string
          example: "商品カテゴリの作成が完了しました"
        data:
          $ref: '#/components/schemas/ProductCategory'

    ProductCategoryUpdatedResponse:
      type: object
      properties:
        message:
          type: string
          example: "商品カテゴリの更新が完了しました"
        data:
          $ref: '#/components/schemas/ProductCategory'

    ProductCategoryDeletedResponse:
      type: object
      properties:
        message:
          type: string
          example: "商品カテゴリの削除が完了しました"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ